from telegram.ext import CommandHandler
from telegram.constants import ParseMode
import random
import string
from shivu import UPDATE_CHAT, SUPPORT_CHAT, CHARA_CHANNEL_ID, required_group_id, PHOTO_URL, OWNER_ID, PARTNER
from shivu import (
    collectionps as collection,
    top_global_groups_collectionps as top_global_groups_collection,
    group_user_totals_collectionps as group_user_totals_collection,
    user_collectionps as user_collection,
    user_totals_collectionps as user_totals_collection,
    shivuups as shivuu,
    shivuups as app,
    applicationps as application,
    SUPPORT_CHATps as SUPPORT,
    UPDATE_CHATps as UPDATE_CHAT_PS,
    dbps as db,
    pmusersps as pmusers,
    ban_collectionps as ban_collection,
    user_countps as user_count,
    chat_dataps as chat_data,
    userbot,
)

HINT_CHANNEL_ID = -1003611322630
SMALL_CAPS_MAP = str.maketrans({
    "a": "ᴀ", "b": "ʙ", "c": "ᴄ", "d": "ᴅ", "e": "ᴇ", "f": "ꜰ", "g": "ɢ", "h": "ʜ", "i": "ɪ",
    "j": "ᴊ", "k": "ᴋ", "l": "ʟ", "m": "ᴍ", "n": "ɴ", "o": "ᴏ", "p": "ᴘ", "q": "ǫ", "r": "ʀ",
    "s": "ꜱ", "t": "ᴛ", "u": "ᴜ", "v": "ᴠ", "w": "ᴡ", "x": "x", "y": "ʏ", "z": "ᴢ",
    "0": "0", "1": "1", "2": "2", "3": "3", "4": "4", "5": "5", "6": "6", "7": "7", "8": "8", "9": "9",
    "|": "|", " ": " ", "-": "-", "/": "/", ":": ":", "_": "_",
})

# Dictionary to store last usage time and generated waifus
last_usage_time = {}
generated_waifus = {}
claimed_waifus = {}


def to_small_caps(text):
    return text.lower().translate(SMALL_CAPS_MAP)


# Function to generate a random string of length 5
def generate_random_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=5))


def build_hint(code):
    hidden_character = code[-1]
    hint_code = f"{code[:-1]}_"
    hint_label = "one digit" if hidden_character.isdigit() else "one letter"
    return hint_code, hint_label


def build_channel_caption(waifu, quantity, code):
    hint_code, hint_label = build_hint(code)
    rarity = to_small_caps(str(waifu['rarity']))
    title = to_small_caps(waifu['name'])
    anime = waifu.get('anime') or 'Unknown'

    return (
        "┏━━━━━━━━━━━━━━┓\n"
        f"⚔️ {title} drop 🧣\n"
        "┗━━━━━━━━━━━━━━┛\n\n"
        f"💀 {waifu['name']}\n"
        f"🌸 {anime}\n"
        f"🔮 {rarity} | 🎯 {quantity}\n\n"
        f"💡 {to_small_caps(f'hint: fill {hint_label}')} → {hint_code}\n\n"
        f"💌 /redeem {hint_code}\n"
        f"✨ {to_small_caps('signature: naruto bot')}"
    )


async def send_hint_drop(context, waifu, quantity, code):
    caption = build_channel_caption(waifu, quantity, code)
    try:
        await context.bot.send_photo(
            chat_id=HINT_CHANNEL_ID,
            photo=waifu['img_url'],
            caption=caption,
        )
    except Exception:
        pass


async def try_delete_redeem_message(update):
    if not getattr(userbot, "is_connected", False):
        return

    message = update.effective_message
    chat = update.effective_chat
    if not message or not chat:
        return

    try:
        await userbot.delete_messages(chat.id, message.id)
    except Exception:
        pass


# Function to handle the waifugen command
async def waifugen(update, context):
    if str(update.effective_user.id) not in PARTNER:
        await update.message.reply_text("You are not authorized to use this command.")
        return

    try:
        waifu_id = context.args[0]
        quantity = int(context.args[1])
    except (IndexError, ValueError):
        await update.message.reply_text("Invalid usage. Usage: /ngen <id> <quantity>")
        return

    waifu = await collection.find_one({'id': waifu_id})
    if not waifu:
        await update.message.reply_text("Invalid waifu ID.")
        return

    code = generate_random_code()
    generated_waifus[code] = {'waifu': waifu, 'quantity': quantity}

    response_text = (
        f"Generated character:\n`{code}`\n"
        f"Name: {waifu['name']}\nRarity: {waifu['rarity']}\nQuantity: {quantity}\n"
        f"For redeem: /redeem {code}"
    )

    await update.message.reply_text(response_text, parse_mode=ParseMode.MARKDOWN)
    await send_hint_drop(context, waifu, quantity, code)

    log_text = (
        f"Character generated by user {update.effective_user.id}:\n"
        f"Code: {code}\nName: {waifu['name']}\nRarity: {waifu['rarity']}\nQuantity: {quantity}"
    )
    for log_user_id in PARTNER:
        await context.bot.send_message(chat_id=log_user_id, text=log_text)


# Function to claim a generated waifu
async def claimwaifu(update, context):
    await try_delete_redeem_message(update)

    code = " ".join(context.args)
    user_id = update.effective_user.id
    user_mention = f"[{update.effective_user.first_name}](tg://user?id={user_id})"

    is_banned = await ban_collection.find_one({"user_id": user_id})
    if is_banned:
        await update.message.reply_text("You are banned from using this command.")
        return

    if code in generated_waifus:
        details = generated_waifus[code]

        if user_id in claimed_waifus.get(code, []):
            await update.message.reply_text("You have already claimed this waifu code.")
            return

        if details['quantity'] > 0:
            waifu = details['waifu']
            await user_collection.update_one(
                {'id': user_id},
                {'$push': {'characters': waifu}}
            )
            await user_count.update_one(
                {'user_id': user_id},
                {'$inc': {'ccount': 1}},
                upsert=True
            )

            rarity = waifu['rarity']
            await user_count.update_one(
                {'user_id': user_id},
                {'$inc': {f'rarity_count.{rarity}': 1}},
                upsert=True
            )

            details['quantity'] -= 1
            claimed_waifus.setdefault(code, []).append(user_id)

            if details['quantity'] == 0:
                del generated_waifus[code]
                del claimed_waifus[code]

            response_text = (
                f"Congratulations {user_mention}! You have received a new waifu for your harem 💍!\n"
                f"Name: {waifu['name']}\nRarity: {waifu['rarity']}\nAnime: {waifu['anime']}\n"
            )
            await update.message.reply_photo(photo=waifu['img_url'], caption=response_text, parse_mode=ParseMode.MARKDOWN)

            log_text = (
                f"Waifu claimed by user {user_id}:\n"
                f"Code: {code}\nName: {waifu['name']}\nRarity: {waifu['rarity']}\nRemaining quantity: {details['quantity']}"
            )
            for log_user_id in PARTNER:
                await context.bot.send_message(chat_id=log_user_id, text=log_text)
        else:
            await update.message.reply_text("This code has already been claimed the maximum number of times.")
    else:
        await update.message.reply_text("Invalid code.")


# Add command handlers to the bot
application.add_handler(CommandHandler("ngen", waifugen))
application.add_handler(CommandHandler("redeem", claimwaifu))
