import random
import string
import datetime
from telegram.ext import CommandHandler
from shivu import application, user_collection, PARTNER, ban_collection
from shivu import LOGGER

last_usage_time = {}
generated_codes = {}

def generate_random_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=5))

async def daily_code(update, context):
    user_id = update.effective_user.id
    is_banned = await ban_collection.find_one({"user_id": user_id})
    if is_banned:
        return

    if user_id in last_usage_time:
        last_time = last_usage_time[user_id]
        current_time = datetime.datetime.now()
        time_diff = current_time - last_time
        if time_diff.total_seconds() < 86400:  # 24 hours
            await update.message.reply_text("⏳ You can only use this command once every 24 hours.")
            return

    code = generate_random_code()
    amount = random.randint(10, 2500)
    quantity = 1

    last_usage_time[user_id] = datetime.datetime.now()
    generated_codes[code] = {'amount': amount, 'quantity': quantity}

    response_text = (
        f"<b>Your daily coin code:</b>\n"
        f"<code>{code}</code>\n"
        f"<b>Amount:</b> {amount} coins\n"
        f"<b>Quantity:</b> {quantity}\n"
        f"<b>To redeem:</b> /credeem {code}"
    )
    await update.message.reply_html(response_text)


async def gen(update, context):
    user_id = str(update.effective_user.id)
    if user_id not in PARTNER:
        await update.message.reply_text("🚫 You are not authorized to generate codes.")
        return

    try:
        amount = float(context.args[0])
        quantity = int(context.args[1])
    except (IndexError, ValueError):
        await update.message.reply_text("❌ Invalid usage. Usage: /gen <amount> <quantity>")
        return

    code = generate_random_code()
    generated_codes[code] = {'amount': amount, 'quantity': quantity}

    response_text = (
        f"<b>Generated coin code:</b>\n"
        f"<code>{code}</code>\n"
        f"<b>Amount:</b> {amount} coins\n"
        f"<b>Quantity:</b> {quantity}\n"
        f"<b>To redeem:</b> /credeem {code}"
    )
    await update.message.reply_html(response_text)

    log_text = (
        f"<b>Code generated by user {user_id}:</b>\n"
        f"<code>{code}</code>\n"
        f"<b>Amount:</b> {amount} coins\n"
        f"<b>Quantity:</b> {quantity}"
    )
    await context.bot.send_message(chat_id=PARTNER, text=log_text, parse_mode='HTML')

async def redeem(update, context):
    code = " ".join(context.args)
    user_id = update.effective_user.id

    # Check if the user is banned
    is_banned = await ban_collection.find_one({"user_id": user_id})
    if is_banned:
        return

    # Check if the code exists
    if code in generated_codes:
        details = generated_codes[code]

        # Check if the code still has a quantity available
        if details['quantity'] > 0:
            # Fetch the user's document
            user_doc = await user_collection.find_one({'id': user_id})

            # Check if the user has already redeemed this code
            redeemed_codes = user_doc.get('redeemed_codes', []) if user_doc else []
            if code in redeemed_codes:
                await update.message.reply_text("❌ You have already redeemed this code.")
                return

            # Add coins to the user's balance
            amount = details['amount']
            await user_collection.update_one(
                {'id': user_id},
                {
                    '$inc': {'coins': amount},
                    '$addToSet': {'redeemed_codes': code}  # Add the code to the redeemed codes list
                },
                upsert=True
            )

            # Decrease the code's quantity and delete if no quantity left
            details['quantity'] -= 1
            if details['quantity'] == 0:
                # Remove the code from `generated_codes`
                del generated_codes[code]

                # Remove the code from all users' `redeemed_codes`
                await user_collection.update_many(
                    {'redeemed_codes': code},
                    {'$pull': {'redeemed_codes': code}}
                )

            await update.message.reply_text(
                f"✅ Code redeemed successfully! {amount} coins added to your account."
            )
        else:
            await update.message.reply_text("❌ This code has reached its redemption limit.")
    else:
        await update.message.reply_text("❌ Invalid code.")


application.add_handler(CommandHandler("dailycode", daily_code))
application.add_handler(CommandHandler("gen", gen))
application.add_handler(CommandHandler("credeem", redeem))
